baseURL = "https://jjmalina.github.io/"
languageCode = "en-us"
title = ""
theme = "hyde-hyde"
pygmentsCodeFences = true
pygmentsStyle = "emacs"

[params]
	authorimage = "jjm.png"
  themeColor = "theme-base-0d"
	description = ""
	highlightjs = false
	copyright = "Jeremiah Malina"

[params.social]
	twitter = "jjmalina"
	github = "jjmalina"

## Main Menu
[[menu.main]]
    name = "Posts"
    weight = 100
    identifier = "posts"
    url = "/posts/"
[[menu.main]]
    name = "About"
    identifier = "about"
    weight = 200
    url = "/about/"
